### ISSUE TITLE
Add support for submitting ProjectQ circuits to Azure Quantum

### ISSUE THREAD

**Issue by guenp** [microsoft/qdk-python#152]
Similar to our Qiskit and Cirq plugins, add a plugin for ProjectQ.

Useful resources:

- https://ionq.com/docs/get-started-with-projectq
- https://projectq.readthedocs.io/_/downloads/en/latest/pdf/

`projectq.backends.CommandPrinter().get_qasm()`

**Comment by anpaz** [comment]
This has now been integrated into the project. Thanks @ssc1729
