### ISSUE TITLE
Understanding the Python package hierarchy around qdk-python

### ISSUE THREAD

**Issue by ltalirz** [microsoft/qdk-python#184]
I'm new to this set of packages, and from looking at the README it wasn't entirely obvious to me how they work together, so I thought it might be useful if I report here what I understood about the package hierarchy (with the goal of then updating the README to make it easier to grok for noobs like me):

 * [`azure-quantum`](https://github.com/microsoft/qdk-python/tree/main/azure-quantum) provides functionality for submitting quantum circuits and problem definitions written in Python. It is independent of the other packages mentioned here.
 * [`qdk`](https://github.com/microsoft/qdk-python/tree/main/qdk) contains (only) `qdk.chemistry`, which provides tools for converting input formats between quantum chemistry codes and those needed by the simulators. It depends on `qsharp`.
   * [`qsharp`](https://github.com/microsoft/QuantumLibraries/tree/main/Python/qsharp) is a metapackage that installs `qsharp-core` and `qsharp-chemistry`
     * [`qsharp-core`](https://github.com/microsoft/iqsharp/tree/main/src/Python/qsharp-core) provides capability to simulate Q# operations from within Python
     * [`qsharp-chemistry`](https://github.com/microsoft/QuantumLibraries/tree/main/Python/qsharp-chemistry) provides `qsharp.chemistry`, which contains convenience classes for interacting with the [`microsoft.quantum.chemistry`](https://github.com/microsoft/QuantumLibraries/tree/main/Chemistry) qsharp package

@guenp Does that sound about right?

If yes, I will then create a follow-up PR to update some of the READMEs.

Some things that confused me
 - The readme mentions qsharp coming soon but it's already here (+ probably no need to mention it in this repository as it's developed elsewhere?)
 - The only use of the `azure.quantum` package in the example notebook appears to be to get the QDK version. Am I understanding correctly that there are currently two routes to submit simulations - one going through `azure.quantum` and one going through `microsoft.quantum.chemistry`? When should one use which?
 - The installation instructions for qdk say to simply `pip install qdk` and then mention to try the example jupyter notebook but that one requires the additional dependencies from the `environment.yml` (not just for rdkit but also for the `jupyter_jsmol` widget etc.)

**Comment by ricardo-espinoza** [comment]
Hi @ltalirz , 

I'm looking at issues in the repo that have been stale for a long time. Those questions have been out for almost a year, so I hope you found that information already. I'm closing the item and I'll reach out to you offline to ask if there are any additional questions or follow ups needed.

**Comment by ltalirz** [comment]
Hi @ricardo-espinoza, besides my question about the hierarchy, this issue was about documenting it for potential contributors e.g. in the README.md or CONTRIBUTING.md of this repository.
There are a number of packages involved, which makes it difficult for users to understand where they need to contribute for a particular.

The other comments in my issue also remain unaddressed.
