### ISSUE TITLE
Clarify licenses used

### ISSUE THREAD

**Issue by BastianZim** [microsoft/qdk-python#207]
Hi, from what I can see the repo is primarily licensed under MIT but the third party notice [file](https://github.com/microsoft/qdk-python/blob/main/NOTICE) includes many other packages that I don't directly see in here.

Are these the licenses of possible dependencies or where are they from? If they're pulled in when running `pip install` they shouldn't really be needed in here, I would assume. Or are they in here for a different reason?

Thanks!

**Comment by guenp** [comment]
@BastianZim, yes, this repo is licensed under MIT. The Third Party Notice file includes the licenses of package dependencies but are not relevant to the code maintained in the repo.
