### ISSUE TITLE
"Finishing" job status is missing from the REST API

### ISSUE THREAD

**Issue by jond01** [microsoft/qdk-python#210]
The "Finishing" status of a job that has been submitted to Azure Quantum is referenced here: 
https://github.com/microsoft/qdk-python/blob/f78537b52f7c478eedc77ea8277dd94212d85950/azure-quantum/azure/quantum/qiskit/job.py#L22-L29

Moreover, I have recorded it when submitting jobs through `az quantum` CLI.

However, this status is missing from the official REST API:
https://github.com/microsoft/qdk-python/blob/f78537b52f7c478eedc77ea8277dd94212d85950/azure-quantum/azure/quantum/_client/models/_quantum_client_enums.py#L36-L44

https://github.com/Azure/azure-rest-api-specs/blob/0a6665506efb86dba686aa87cab3bdd836fac36a/specification/quantum/data-plane/Microsoft.Quantum/preview/2021-11-01-preview/quantum.json#L424-L439

I hope that this is the appropriate repo for this issue.

-----

The following link too does not mention this status:
https://docs.microsoft.com/en-us/azure/quantum/how-to-work-with-jobs#monitoring-jobs

**Comment by guenp** [comment]
@jond01, the Azure Quantum API does not specify a "Finishing" job status, so it is mapped onto `JobStatus.RUNNING` instead.
Did this cause any issues for you when using the Qiskit integration?

**Comment by anpaz** [comment]
Working as designed.
