### ISSUE TITLE
Service Principal auth broken in latest azure-quantum

### ISSUE THREAD

**Issue by Mobius5150** [microsoft/qdk-python#22]
Using the latest version of the azure-quantum package and following the [official service principal auth instructions](https://docs.microsoft.com/en-us/azure/quantum/optimization-authenticate-service-principal) shows that auth is currently broken. Attempting to authenticate yields the following exception:

```
  File "\Python\Python36\lib\site-packages\msrest\pipeline\__init__.py", line 197, in run
    return first_node.send(pipeline_request, **kwargs)  # type: ignore
  File "\Python\Python36\lib\site-packages\msrest\pipeline\__init__.py", line 150, in send
    response = self.next.send(request, **kwargs)
  File "\Python\Python36\lib\site-packages\msrest\pipeline\requests.py", line 68, in send
    request.context.session = session = self._creds.signed_session()
  File "\Python\Python36\lib\site-packages\msrest\authentication.py", line 118, in signed_session
    header = "{} {}".format(self.scheme, self.token['access_token'])
TypeError: 'ServicePrincipalCredentials' object is not subscriptable
```

It seems that this is also using an old pattern, and that Azure SDKs are moving to the `azure-identity` package instead of `azure-common`.

**Comment by ashwinmayya** [comment]
Please using the following command to revert to an older version of the package to unblock this scenario while we fix the issue.
pip install azure-quantum==0.15.2101.125897 --force-reinstall
