### ISSUE TITLE
Idea: simplify and streamline Qiskit and Azure Quantum workflow

### ISSUE THREAD

**Issue by guenp** [microsoft/qdk-python#228]
Some ideas after discussing with @xinyi-joffre and @achocron to simplify and streamline how you can submit Qiskit/Cirq/Q# circuits to a Quantum Workspace:

- Pass any kind of problem to workspace.submit:
```python
circuit = QuantumCircuit()
... # Create your circuit here

job = workspace.submit(circuit, target="ionq.simulator", shots=1000) # This interface will be consistent between targets. We only change circuit.
```

This will make the interface more scalable and easier to use/explain to new users.

- Make Qiskit-specific abstractions available for advanced scenarios. I.e., we keep the `azure.quantum.qiskit`.

- Create a standardized `Result` object.
   - `Result.to_qiskit_result()` : Convert `Result` into `qiskit.Result`

**Comment by anpaz** [comment]
There are a couple of downsides to this approach:
1. You can submit a lot of different payloads to a workspace, not only Qiskit and Cirq, but provider-specific formats and/or Optimization jobs which are not circuit based.
2. Even the same circuit can be serialized differently depending on the target, and only the target knows this serialization
3. For Qiskit and Cirq, our goal is not to ask the users to use our APIs, but to leverage the existing Qiskit/Cirq APIs, for those scenarios it already works as suggested.

As such, for now we're not planning to take this ideas and we might revisit them in the future.
