### ISSUE TITLE
Request for removal of workaround of 0.16.2105.141895b1

### ISSUE THREAD

**Issue by murayama-sbm-toshiba** [microsoft/qdk-python#235]
Could you please remove the workaround of 0.16.2105.141895b1 from the latest qdk?
When I execute a job to Toshiba SBM solver using qdk (version: 0.21.2112.180703), it output the following warning message regardless of the compress flag specified.

```
/home/azureuser/anaconda3/envs/qsharp-env/lib/python3.7/site-packages/azure/quantum/target/solvers.py:127: UserWarning: The service no UserWarning: The service no longer accepts payloads that are not compressed with gzip encoding. Ignoring compress flag.
  Ignoring compress flag.")
```

Until now, the Toshiba SBM solver did not support the GZIP format for input problem files. Therefore, in version 0.16.2105.141895b1, we were provided a workaround to force the compress flag to be set to false for the Toshiba SBM solver.
However, the Toshiba SBM solver now supports the GZIP format, and the workaround is no longer necessary.

**Comment by guenp** [comment]
I will close this since it was fixed in #241. The fix will be available in our February release.
