### ISSUE TITLE
Test function needs to be async

### ISSUE THREAD

**Issue by IsraelMiles** [microsoft/qdk-python#258]
A Python test is marked as `@pytest.mark.asyncio` but is not async. See here:
[qdk-python/test_aio_solvers.py at 07c3ea31d9e53aac154589f54a9ada6482bd3242 · microsoft/qdk-python (github.com)](https://github.com/microsoft/qdk-python/blob/07c3ea31d9e53aac154589f54a9ada6482bd3242/azure-quantum/tests/unit/aio/test_aio_solvers.py)

@guenp

**Comment by anpaz** [comment]
Done.
