### ISSUE TITLE
Missing method retrieve_job on Honeywell/Quantinuum backend

### ISSUE THREAD

**Issue by guenp** [microsoft/qdk-python#263]
For ionq qpu, I used the following code block 

 
```python
simulator = myprovider.get_backend('ionq.qpu')

retrieved =simulator.retrieve_job("myid")
```
 

But similar code block does not work with Honeywell 

```python
simulator = provider.get_backend("honeywell.hqs-lt-s2")

retrieved =simulator.retrieve_job("myid")
```
 

It results in the following error message

```python
AttributeError: 'HoneywellQPUBackend' object has no attribute 'retrieve_job'
```

**Comment by ricardo-espinoza** [comment]
With the changes in #278 , the method `retrieve_job()` is now part of the base implementation and is available to all providers.
