### ISSUE TITLE
VQE sample is not using the correct stateType for the UCCSD ansatz

### ISSUE THREAD

**Issue by guenp** [microsoft/qdk-python#264]
The sample in this notebook: https://github.com/microsoft/qdk-python/blob/main/examples/chemistry/Molecule.ipynb
is loading the wrong ansatz. The stateType is read from the Broombridge file but it is set to `2` (Sparse_Multi_Configurational) instead of `3` (UCCSD).

**Comment by xinyi-joffre** [comment]
Closing since qdk.chemistry package is deprecated, and the examples have been removed.
