### ISSUE TITLE
Workspace does not handle token refresh automatically

### ISSUE THREAD

**Issue by Mobius5150** [microsoft/qdk-python#31]
When running a script that runs for 1hr+ invariably the short-lived access token will expire. When this happens the user will receive an `Unauthorized` error and needs to call `workspace.login()` again.

This is not ideal behavior - instead, the SDK should transparently update it's internal credential before it expires so that users don't need to handle this scenario.

**Comment by vxfield** [comment]
This issue should  now be obsolete with the May2021 release that uses a different authentication pipeline handled by Azure.Identity and the `workspace.login()` method has been deprecated.

**Comment by vxfield** [comment]
Obsolete/fixed using the `Azure.Identity` authentication credentials released in May 2021 with #54 and #69.
