### ISSUE TITLE
Run live tests during CI

### ISSUE THREAD

**Issue by anpaz** [microsoft/qdk-python#319]
Our CI normally runs unit-tests in recorded mode and run them live only during releases.
Recently, we've found multiple tests failing during release namely because we did changes that work with recordings but failed during live tests.
Since live-tests can be flaky or fail due to service errors, we should run these live tests but not fail the CI pipeline if they fail.

**Comment by ricardo-espinoza** [comment]
These tests are already running live in automation, so this can be closed.
