### ISSUE TITLE
"shots is not a known attribute of class JobDetails and will be ignored" when running VQE

### ISSUE THREAD

**Issue by guenp** [microsoft/qdk-python#326]
When running the Azure Quantum sample [VQE](https://github.com/microsoft/Quantum/tree/feature/samples-gallery/samples/azure-quantum/variational-quantum-eigensolver), running on the Quantinuum emulator raises the following warning:

```
shots is not a known attribute of class <class 'azure.quantum._client.models._models_py3.JobDetails'> and will be ignored
```

It looks like the `Quantinuum` backend does not support `shots`, see: [quantinuum.py](https://github.com/microsoft/qdk-python/blob/37942c446ffe8ae88a25241886ab8dfa783a0545/azure-quantum/azure/quantum/qiskit/backends/quantinuum.py#L71).

**Comment by guenp** [comment]
Run this sample to reproduce the issue: https://github.com/microsoft/Quantum/blob/feature/samples-gallery/samples/azure-quantum/variational-quantum-eigensolver/VQE-qiskit-hydrogen-quantinuum-emulator.ipynb

**Comment by frtibble** [comment]
+1 this caused some confusion for a customer I was speaking with too
