### ISSUE TITLE
JSMol widget does not load for some users

### ISSUE THREAD

**Issue by guenp** [microsoft/qdk-python#34]
@vxfield reported that the JSMol widget did not work for him:
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/4041805/111707329-14308100-8801-11eb-86b1-08c3f5f841f8.png)

We will need to investigate this further but it might be related to the JS libraries not being loaded properly.

**Comment by ltalirz** [comment]
For me not even the JSmol spinner is shown.

![image](https://user-images.githubusercontent.com/1053245/142648550-997cafa0-522f-4bd4-b3a5-871a8541c434.png)

These are the errors on the console
![image](https://user-images.githubusercontent.com/1053245/142648698-eccf9ff9-1c60-43de-8146-03b456accaa0.png)

I'm running in a conda environment created from the `environment.yml` from the `qdk` folder under Ubuntu 20.04 (WSL).

**Comment by ltalirz** [comment]
This is an upstream issue in `jupyter-jsmol`

Tracking in https://github.com/fekad/jupyter-jsmol/issues/37

**Comment by ltalirz** [comment]
Fixed by `jupyter-jsmol` release `v2022.1.0`
https://github.com/fekad/jupyter-jsmol/releases/tag/v2022.1.0

This issue can be closed.
