### ISSUE TITLE
environment.yml does not have azure-quantum package in it

### ISSUE THREAD

**Issue by lwoodyiii** [microsoft/qdk-python#346]
https://github.com/microsoft/qdk-python/blob/main/azure-quantum/environment.yml does not list azure-quantum package.

**Comment by anpaz** [comment]
This is on purpose. The environment.yml is what we use to setup the local environment to develop azure quantum. After setting up your conda environment you still need to do `pip install -e .` in the environment, to install azure quantum in development mode.

For more detailed instructions on how to setup your environment, please take a look at: https://github.com/microsoft/qdk-python/blob/main/CONTRIBUTING.md
