### ISSUE TITLE
Set up dependabot to automatically keep dependency versions up to date

### ISSUE THREAD

**Issue by guenp** [microsoft/qdk-python#41]
See comment by @jenshnielsen here: https://github.com/microsoft/qdk-python/pull/40#issuecomment-816473328

We should set up [dependabot](https://dependabot.com/) to keep the requirements that we perform most of the actual ci testing against (in requirements.txt) up to date and automatically open new pull requests when a new package is released. See also the [Qcodes](https://github.com/QCoDeS/Qcodes) repo for how this is set up.

**Comment by hxri** [comment]
Hi Is this done? If not can I work on it?

**Comment by guenp** [comment]
Hi @hxri! No not yet, if you're still interested please do! I'll add a Hacktoberfest label as well.
