### ISSUE TITLE
Support `azure-quantum[qiskit]` installation on macOS M1

### ISSUE THREAD

**Issue by jond01** [microsoft/qdk-python#410]
Installing the `azure-quantum` package with the `qiskit` extras on macOS with ARM processors (e.g. M1) is not supported currently, because of this fixed dependency:
https://github.com/microsoft/qdk-python/blob/bc4ae3a5bb1a84cfcb7f68c3e3e2f1d7f38f69f5/azure-quantum/setup.py#L86
So the dependency path looks like:
```
azure-quantum 0.27.244707 Python client for Azure Quantum
├── qiskit-qir >=0.2,<0.3
│   ├── pyqir-generator 0.4.2a1 
```

However, the latest version of `pyqir` supports ARM processors, see https://github.com/microsoft/qiskit-qir/issues/34 (which has to be addressed first).

**Comment by jond01** [comment]
Ok, it looks like v0.27.238334 solved the issue:
https://github.com/microsoft/qdk-python/blob/975d08bf7aea9bae7778800a6ae0f5e00fc74cd2/azure-quantum/setup.py#L86

This is still relevant on the main branch, though

**Comment by idavis** [comment]
@jond01 This will be handled in #420 which updates to PyQIR 0.8 and qiskit-qir 0.3.1
