### ISSUE TITLE
Set up main branch protection so one cannot push to main without a PR

### ISSUE THREAD

**Issue by vxfield** [microsoft/qdk-python#43]
I accidentally pushed a [commit](https://github.com/microsoft/qdk-python/commit/55c8af71a108e4926fa5396f1b23e5733fbc642f) to main when I though I was pushing to my own branch. I fixed it by [reverting the commit ](https://github.com/microsoft/qdk-python/commit/4e35136228878a72f2b6aad53a841b6e02618f60)(with another direct push to main!).

So we need to enable `main` branch protection so it does not happen again without going thru a proper PR review process.

**Comment by vxfield** [comment]
@guenp, @cgranade: FYI

**Comment by guenp** [comment]
@vxfield thanks for raising this issue. I checked and branch protection was set up already but I forgot to check the "Include administrators" box! This is now checked so pushing to `main` should now be blocked for everyone.

**Comment by vxfield** [comment]
Ok, so I'll test it by trying to do a harmless push into a readme file.
Then we can close this issue.

**Comment by guenp** [comment]
Sounds good, thank you! I can confirm it works for me:
```
remote: Resolving deltas: 100% (2/2), completed with 2 local objects.
remote: error: GH006: Protected branch update failed for refs/heads/main.
remote: error: 20 of 20 required status checks are expected. At least 1 approving review is required by reviewers with write access.
To github.com:microsoft/qdk-python.git
 ! [remote rejected] main -> main (protected branch hook declined)
error: failed to push some refs to 'git@github.com:microsoft/qdk-python.git'
```

**Comment by vxfield** [comment]
Ok then. Let's close the issue. Thanks, @guenp!
