### ISSUE TITLE
azure-quantum tar.gz package does not include requirements.txt file

### ISSUE THREAD

**Issue by guenp** [microsoft/qdk-python#57]
When downloading the tar.gz file from PyPI, the requirements.txt file seems to be missing:
https://pypi.org/project/azure-quantum/#files

It looks like we need to add a MANIFEST file to include this as part of the build artifact.

**Comment by vxfield** [comment]
@guenp, the [setup.py](https://github.com/microsoft/qdk-python/blob/24ac906a456467f9690ddf041b00ca3b44846556/azure-quantum/setup.py#L63) reads the content of the requirements.txt file and [pass it](https://github.com/microsoft/qdk-python/blob/24ac906a456467f9690ddf041b00ca3b44846556/azure-quantum/setup.py#L81) to the `setuptools.setup` call.

So I don't think we need to add `requirements.txt` to the package, do we?

**Comment by guenp** [comment]
@vxfield this shows up when trying to install the package from the tar.gz file directly:
```
$ pip install /mnt/c/Users/guenp/Downloads/azure-quantum-0.18.2106.148911.tar.gz
Processing /mnt/c/Users/guenp/Downloads/azure-quantum-0.18.2106.148911.tar.gz
    ERROR: Command errored out with exit status 1:
     command: /home/guen/anaconda3/envs/azure-quantum/bin/python3.7 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-m142_vo7/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-m142_vo7/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-am70m1w2
         cwd: /tmp/pip-req-build-m142_vo7/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-m142_vo7/setup.py", line 63, in <module>
        with open("./requirements.txt", "r") as fh:
    FileNotFoundError: [Errno 2] No such file or directory: './requirements.txt'
    ----------------------------------------
WARNING: Discarding file:///mnt/c/Users/guenp/Downloads/azure-quantum-0.18.2106.148911.tar.gz. Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by AnudeepGunukula** [comment]
Hi @guenp . i would like to work on this issue.
is this still open ?

**Comment by AnudeepGunukula** [comment]
Kindly let me know is this issue got resolved with pr #81 
because still the error remains same when i tried to install like you
![image](https://user-images.githubusercontent.com/55506841/130018877-1ea3970b-8b6e-4a05-a0fa-401b6f985e29.png)

**Comment by guenp** [comment]
@AnudeepGunukula Thanks so much, yes the issue is still open so please feel free to give it a stab.

**Comment by AnudeepGunukula** [comment]
Hi @guenp , can you please specify the path where to add the requirements.txt in the project.
because i was seeing, already azure-quantum folder contains requirements.txt file.
only the pypy package doesn't having it in root folder.

**Comment by guenp** [comment]
@AnudeepGunukula, that's right, we already have the file so we don't need to add it; however, we do need to add a `MANIFEST` file to include the `requirements.txt` file as part of the packaged wheel and `.tar.gz` file. That file should go in the `{root}/azure-quantum/` folder. You can find instructions on  how to do that here: [Python docs: Creating a Source Distribution](https://docs.python.org/3/distutils/sourcedist.html)

**Comment by AnudeepGunukula** [comment]
Hi @guenp . i had made a pr
kindly review it and let me know if any changes required.
